# .github/workflows/deploy.yml

name: CD (Continuous Deployment)

on:
  push:
    branches: [ main, develop ]

jobs:
  test:
    # ... (el trabajo de prueba se queda igual) ...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd functions && npm install

      # ... (la configuración de las claves de Stripe se queda igual) ...
      
      # ¡NUEVO! Inyectamos la configuración de Firebase en el index.html
      - name: Inject Firebase Config
        run: |
          # Reemplazamos un marcador de posición en index.html con el secreto
          sed -i 's|__FIREBASE_CONFIG__|${{ secrets.FIREBASE_CONFIG }}|g' public/index.html

      # Despliega en Firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          action: deploy
          project_id: 'bobadragonapp'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
